spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/photography_agenda
spring.datasource.username=postgres
spring.datasource.password=98829893

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
